[package]
name = "optimal-layout"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
# bevy_math = "0.16.1"
rand = "0.9.2"
chrono = "0.4.41"
iyes_perf_ui = "0.5"

serde = "1"
serde_yml = "0.0.12"
